valuesFilePath: ./values.yml
__globals:
  cronTriggerName: &cronTriggerName '{{ default "cron_trigger" .Values.metadata.cronTriggerResourceName }}'
resources:
  - name: artifact_cleanup_parent_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repo.path }}
      gitProvider: {{ .Values.repo.integrationName }}
      branches:
        include: {{ .Values.repo.branchPattern }}

  {{ if eq true .Values.controls.cron.enabled }}
  - name: *cronTriggerName
    type: CronTrigger
    configuration:
      interval: "{{ default "0 0 5 ? * 1" .Values.controls.cron.expression }}"
  {{ end }}

pipelines:
  - name: PythonScript
    steps:
      - name: first_step
        type: Bash
        configuration:
          integrations:
            - name: webhook_basic_auth_b64_encoded
          environmentVariables:
            RESOURCE_PATH: $res_{{ .Values.namePrefix }}_repo_resourcePath
          inputResources:
            - name: {{ .Values.namePrefix }}_repo
        {{ if eq true .Values.controls.cron.enabled }}
            - name: *cronTriggerName
        {{ end }}
        execution:
          onStart:
            - echo 'on start!'
          onExecute:
            - pushd $RESOURCE_PATH # This is needed to change working dir to the root of the checked-out repository
            - pip install requests # The Python script relies on Requests...you could use urlLib or some other Python std lib HTTP Client
            - python3 ./test.py