valuesFilePath: ./values.yml
__globals:
  cronTriggerName: &cronTriggerName '{{ default "cron_trigger" .Values.metadata.cronTriggerResourceName }}'
resources:
  {{ if .Values.repo.integrationName }}
  - name: {{ .Values.namePrefix }}_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repo.path }}
      gitProvider: {{ .Values.repo.integrationName }}
      branches:
        include: {{ .Values.repo.branchPattern }}
  {{ end }}

  {{ if eq true .Values.controls.cron.enabled }}
  - name: *cronTriggerName
    type: CronTrigger
    configuration:
      interval: "{{ default "0 0 5 ? * 1" .Values.controls.cron.expression }}"
    {{ end }}

pipelines:
  - name: PythonScript
    steps:
      - name: first_step
        type: Bash
        configuration:
          integrations:
            - name: webhook_basic_auth_b64_encoded
          environmentVariables:
            RESOURCE_PATH: $res_{{ .Values.namePrefix }}_repo_resourcePath
          inputResources:
            - name: {{ .Values.namePrefix }}_repo
        {{ if eq true .Values.controls.cron.enabled }}
            - name: *cronTriggerName
        {{ end }}
        execution:
          onStart:
            - echo 'on start!'
          onExecute:
            - echo 'Exploring Directory Structure'
            - pushd $RESOURCE_PATH
            - ls -lah
            - which python3
            - which pip
            - pip install requests
            - python3 ./test.py