valuesFilePath: ./values.yml
__globals:
  cronTriggerName: &cronTriggerName '{{ default "cron_trigger" .Values.metadata.cronTriggerResourceName }}'
resources:
  {{ if .Values.repo.integrationName }}
  - name: {{ .Values.namePrefix }}_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repo.path }}
      gitProvider: {{ .Values.repo.integrationName }}
      branches:
        include: {{ .Values.repo.branchPattern }}
  {{ end }}

  {{ if eq true .Values.controls.cron.enabled }}
  - name: *cronTriggerName
    type: CronTrigger
    configuration:
      interval: "{{ default "0 0 5 ? * 1" .Values.controls.cron.expression }}"
    {{ end }}

pipelines:
  - name: PythonScript
    steps:
      - name: git_checkout
        type: Bash
        inputResources:
          - name: *cronTriggerName
        execution:
          onStart:
            - echo 'on start!'
          onExecute:
            - echo 'on execute!'
      - name: execute_python
        type: Bash
        inputResources:
          - name: git_checkout
        execution:
          onStart:
            - echo 'on start!'
          onExecute:
            - echo 'on start!'
          onComplete:
            - echo 'on Complete!'
