namePrefix: artifact_cleanup_parent
metadata:
  cronTriggerResourceName: cron_trigger
controls:
  cron:
    enabled: true
    expression: "*/3 * * * *"
repo:
  # Before creating your Pipeline Source, create an integration for one of the
  # source control providers and put the integration name here.
  integrationName: Github_tomjfrog

  # this is the full repository path. Usually org/repo or user/project
  # depending on which source control you use.
  path: "tomjfrog/python-in-pipelines"

  # branchPattern is a regex, so you could listen to all
  # features, for example, with "^feature.*"
  branchPattern: "^main$"